services:
  - type: web
    name: soulseer
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SIGNING_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        value: https://soulseer-create-default-rtdb.firebaseio.com
      - key: FIREBASE_PROJECT_ID
        value: soulseer-create
      - key: FIREBASE_STORAGE_BUCKET
        value: soulseer-create.firebasestorage.app