services:
  - type: web
    name: soulseer
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Aj2RfUtlYc4I@ep-snowy-tooth-a4pqf58x-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SIGNING_SECRET
        sync: false
      - key: WEBRTC_ICE_SERVERS
        value: '[{"urls":"stun:stun.l.google.com:19302"},{"urls":"stun:stun1.l.google.com:19302"}]'
      - key: WEBRTC_TURN_SERVERS
        value: relay1.expressturn.com:3480
      - key: WEBRTC_TURN_SERVERS_USERNAME
        value: relay1.expressturn.com:3480
      - key: WEBRTC_TURN_SERVERS_PASSWORD
        value: M5zys3Dh++iwdoCz4xJF3SWHS2M=
      - key: JWT_SECRET
        sync: false # This should be set directly in Render's secret management